<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script>

    function supprime (etudiant) {
        if (confirm('Vous etes sur de vouloir supprimer cet etudiant de la BASE?')) {
			alert('Votre etudiant a ete supprime de la BASE');
			$.ajax({
				url      : document.location.protocol + '//localhost:82/Zend2/public/exam/supp/'+etudiant,
				dataType : 'json',
				success  : function (data) {                
					alert("sucess");

				}
			});
		}	 
	}
//Appel AJAX:
//$(document).ready(supprime ());



</script> 
 
 
 <?php
 // module/Exam/view/exam/exam/index.phtml:

 $title = 'My exam';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('exam', array('action'=>'add'));?>">Ajouter un nouveau etudiant</a>
 </p>

 <table class="table">
 <tr>
     <th>Prenom</th>
     <th>Nom</th>
     <th>Note </th>
     <th>Exercices </th>
	 <th>Fonctions</th>
 </tr>
 <?php foreach ($exams as $exam) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($exam->prenom);?></td>
     <td><?php echo $this->escapeHtml($exam->nom);?></td>
	 <td><?php echo $this->escapeHtml($exam->note);?></td>
	 <td><?php echo $this->escapeHtml($exam->exercices);?></td>
	 
     <td>
         <a href="<?php echo $this->url('exam',
             array('action'=>'edit', 'id' => $exam->id));?>">Ajouter une Note</a><br>
         <a href="<?php echo $this->url('exam',
             array('action'=>'delete', 'id' => $exam->id));?>">Supprimer Personne</a><br>
		 <a onClick="supprime(<?php echo $exam->id?>);" href="">Supprimer en JSON</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 
 

